version: '3.1'

services:
  db:
    image: postgres
    restart: 'always'
    environment:
      - POSTGRES_DB=FinalPaper
      - POSTGRES_USER=FinalPaper
      - POSTGRES_PASSWORD=FinalPaper
    ports:
      - '5442:5432'

  db-test:
    image: postgres
    restart: 'always'
    environment:
      - POSTGRES_DB=FinalPaperTest
      - POSTGRES_USER=FinalPaperTest
      - POSTGRES_PASSWORD=FinalPaperTest
    ports:
      - '5443:5432'
  db-mongo:
    image: mongo
    restart: 'always'
    environment:
      - MONGO_INITDB_DATABASE=FinalPapper
    ports:
      - '27017:27017'
