version: '3.1'

services:
  db:
    image: postgres
    restart: 'always'
    environment:
      - POSTGRES_DB=FinalPaper
      - POSTGRES_USER=FinalPaper
      - POSTGRES_PASSWORD=FinalPaper
    ports:
      - '5444:5432'


