name: Node CI

on: [push]

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.0"
    - name: Install and test
      run: |
        cd fp-client/
        npm i
        npm test
      env:
        CI: true

