name: Integration
on: push
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: "15.14.0"

      - name: Install Packages for Root
        run: npm ci
        env:
          CI: true

      - name: Bootstrap Dependencies
        run: npx lerna bootstrap

      - name: Run Eslint
        run: npm run lint

      - name: Run Unit Test
        run: npm test
