name: Server Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15"
      - name: Install and Test
        run: ./.github/scripts/test.sh
        env:
          CI: true
