name: Server Integration

on:
  push:
    branches:
      - main
      - "feat/*"
      - "fix/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15"
      - name: Install and Test
        run: bash ./.github/scripts/test.sh
        env:
          CI: true
