name: Server Integration

on:
  push:
    branches:
      - "feat/**"
      - "fix/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15"
      - name: Install and Test
        run: |
          cd packages/server/
          npm ci
          npm test
        env:
          CI: true
