name: Server CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install pipenv
        run: sudo apt install -y pipenv
      - name: Install and Test
        run: |
          cd smart-object/
          pipenv install
          pipenv run test
